<a href="https://colab.research.google.com/github/aryansanchiya/Machine-Learning/blob/main/Exercise_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
random_tensor = torch.rand(7,7)

In [3]:
random_tensor

tensor([[0.8836, 0.6187, 0.9546, 0.3554, 0.4340, 0.9001, 0.3974],
        [0.6246, 0.0753, 0.1107, 0.8346, 0.5026, 0.6902, 0.9516],
        [0.8389, 0.0366, 0.8437, 0.0456, 0.8321, 0.6547, 0.9755],
        [0.1906, 0.0647, 0.8558, 0.0401, 0.8953, 0.9837, 0.3457],
        [0.3134, 0.8588, 0.9645, 0.3169, 0.2657, 0.9533, 0.5799],
        [0.4193, 0.7535, 0.8822, 0.8755, 0.2536, 0.2145, 0.9773],
        [0.0069, 0.9750, 0.8177, 0.0692, 0.2118, 0.1422, 0.1133]])

In [4]:
random_tensor2 = torch.rand(7,1)

In [5]:
random_tensor2.T

tensor([[0.4733, 0.1714, 0.0820, 0.4627, 0.2027, 0.4668, 0.5867]])

In [6]:
random_tensor.T

tensor([[0.8836, 0.6246, 0.8389, 0.1906, 0.3134, 0.4193, 0.0069],
        [0.6187, 0.0753, 0.0366, 0.0647, 0.8588, 0.7535, 0.9750],
        [0.9546, 0.1107, 0.8437, 0.8558, 0.9645, 0.8822, 0.8177],
        [0.3554, 0.8346, 0.0456, 0.0401, 0.3169, 0.8755, 0.0692],
        [0.4340, 0.5026, 0.8321, 0.8953, 0.2657, 0.2536, 0.2118],
        [0.9001, 0.6902, 0.6547, 0.9837, 0.9533, 0.2145, 0.1422],
        [0.3974, 0.9516, 0.9755, 0.3457, 0.5799, 0.9773, 0.1133]])

In [7]:
torch.matmul(random_tensor,random_tensor2)

tensor([[1.5083],
        [1.6862],
        [1.5403],
        [1.0336],
        [1.3604],
        [1.5300],
        [0.4452]])

In [8]:
#Random_seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_x = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor_y = torch.rand(1,7)


In [9]:
tensor_x

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [10]:
tensor_y

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [11]:
tensor_y.T

tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])

In [12]:
tensor_y.shape

torch.Size([1, 7])

In [13]:
torch.matmul(tensor_y,tensor_x)

tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752]])

In [17]:
torch.manual_seed(1234)
tensor_a = torch.rand(2,3)
torch.manual_seed(1234)
tensor_b = torch.rand(2,3)

In [18]:
tensor_a,tensor_b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

In [31]:
if torch.cuda.is_available():
  torch.cuda.manual_seed(1234)
  torch.cuda.manual_seed_all(1234)

  tensor_a_gpu = torch.rand(2,3).cuda()
  tensor_b_gpu = torch.rand(2,3).cuda()

  print(tensor_a_gpu)
  print(tensor_b_gpu)

  matm = torch.matmul(tensor_a_gpu.T,tensor_b_gpu)

  print(matm)


tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
tensor([[0.7749, 0.8208, 0.2793],
        [0.6817, 0.2837, 0.6567]], device='cuda:0')
tensor([[0.2661, 0.1365, 0.2321],
        [0.8970, 0.6066, 0.6454],
        [0.9059, 0.7128, 0.5580]], device='cuda:0')


In [32]:
 matm.min()

tensor(0.1365, device='cuda:0')

In [26]:
matm.max()

tensor(0.5584, device='cuda:0')

In [28]:
matm.argmin()

tensor(1, device='cuda:0')

In [29]:
matm.argmax()

tensor(8, device='cuda:0')