<a href="https://colab.research.google.com/github/aryansanchiya/Machine-Learning/blob/main/Tensor_Datatypes_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
#https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32656962#overview

In [3]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [4]:
type(float_32_tensor)

torch.Tensor

In [5]:
float_32_tensor.dtype

torch.float32

In [10]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor.dtype

torch.float16

In [8]:
#"dtype" arguement is used for create diffrent kind of datatypes.

In [11]:
#How to change the datatype ?

In [15]:
new_float_64 = float_32_tensor.type(torch.float64)

In [16]:
new_float_64.dtype

torch.float64

Tutorial - 24

In [27]:
#https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32656964#questions

In [17]:
#Operations on diffrent datatypes

In [20]:
int_32_tensor = torch.tensor([3, 4, 5],
                             dtype = torch.int32)
float_32_tensor

tensor([3., 6., 9.])

In [19]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 45.])

In [21]:
#Conclusion is that it works!

In [22]:
#"tensor.shape" is used to know shape of the tensors
#"tensor.dtype" is used to know datatype of the tensors
#'tensor.device" is used to know the device of the tensors (cpu/gpu)

In [23]:
some_tensor = torch.rand(3,4)

In [24]:
some_tensor

tensor([[0.1478, 0.9802, 0.2238, 0.8624],
        [0.3000, 0.1273, 0.6083, 0.3923],
        [0.7102, 0.6185, 0.9551, 0.5857]])

In [26]:
print("Datatype:", some_tensor.dtype)
print("Shape:",some_tensor.shape)
print("Device:",some_tensor.device)

Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


## **`Manipulating Tensors`**
[Tutorial - 26](https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32656966#content)

***`Tensor Operation:`***



---


1.   Addition
2.   Multiplication (Element Wise)
3.   Division
4.   Matrix Multiplication





In [28]:
new_tensor = torch.tensor([1, 2, 3])
new_tensor + 10

tensor([11, 12, 13])

In [29]:
new_tensor - 10

tensor([-9, -8, -7])

In [30]:
new_tensor * 100

tensor([100, 200, 300])

In [31]:
new_tensor / 1

tensor([1., 2., 3.])

In [32]:
new_tensor % 1

tensor([0, 0, 0])

In [33]:
new_tensor // 1

tensor([1, 2, 3])

In [44]:
new_tensor2 = torch.tensor([4, 5 ,6])

In [45]:
torch.matmul(new_tensor,new_tensor2)

tensor(32)

There are mainly two ways to perform multiplication in neural network and deep learning:


1.   Elementwise Multiplication
2.   Matrix Multiplication



In [46]:
new_tensor3 = torch.tensor([[1,2,3],
                            [4,5,6]])
new_tensor3

tensor([[1, 2, 3],
        [4, 5, 6]])

In [48]:
new_tensor4 = torch.tensor([[7,8],
                            [9,10],
                            [11,12]])
new_tensor4

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [49]:
torch.matmul(new_tensor3,new_tensor4)

tensor([[ 58,  64],
        [139, 154]])

There are mainly two rules which should be rememberd:
1. The **inner dimension** must match:

  `(3,2) @ (3,2)` Wont work

  `(2,3) @ (3,2)` will work

  `(3,2) @ (2,3)`
 will work

2. The resulting matrix has a shape of **outer dimension**.

  `(2,3) @ (3,2) -> (2,2)`

  `(3,2) @ (2,3) -> (3,3)`

Tensor Shape errors - [Tutorial - 29](https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32656976#content)

In [50]:
Tensor_A = torch.tensor([[1,2,3],
                         [4,5,6]])
Tensor_A

tensor([[1, 2, 3],
        [4, 5, 6]])

In [51]:
Tensor_B = torch.tensor([[7,8,9],
                         [10,11,12]])
Tensor_B

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [59]:
torch.matmul(Tensor_A,Tensor_B)

tensor([[ 50,  68],
        [122, 167]])

In [53]:
Tensor_A.shape

torch.Size([2, 3])

In [54]:
Tensor_B.shape

torch.Size([2, 3])

`Tensor_A and Tensor_B shapes cannot be multiplied` - To hand this kind of error, we can use **Transpose method**, which can be use with **T**.

In [64]:
Tensor_B = Tensor_B.T #Transpose method

In [65]:
Tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [66]:
torch.matmul(Tensor_A,Tensor_B)

tensor([[ 50,  68],
        [122, 167]])