<a href="https://colab.research.google.com/github/aryansanchiya/Machine-Learning/blob/main/Tensor_Datatypes_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
#https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32656962#overview

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
type(float_32_tensor)

torch.Tensor

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor.dtype

torch.float16

In [ ]:
#"dtype" arguement is used for create diffrent kind of datatypes.

In [ ]:
#How to change the datatype ?

In [ ]:
new_float_64 = float_32_tensor.type(torch.float64)

In [ ]:
new_float_64.dtype

torch.float64

Tutorial - 24

In [ ]:
#https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32656964#questions

In [ ]:
#Operations on diffrent datatypes

In [ ]:
int_32_tensor = torch.tensor([3, 4, 5],
                             dtype = torch.int32)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 45.])

In [ ]:
#Conclusion is that it works!

In [ ]:
#"tensor.shape" is used to know shape of the tensors
#"tensor.dtype" is used to know datatype of the tensors
#'tensor.device" is used to know the device of the tensors (cpu/gpu)

In [ ]:
some_tensor = torch.rand(3,4)

In [ ]:
some_tensor

tensor([[0.1478, 0.9802, 0.2238, 0.8624],
        [0.3000, 0.1273, 0.6083, 0.3923],
        [0.7102, 0.6185, 0.9551, 0.5857]])

In [ ]:
print("Datatype:", some_tensor.dtype)
print("Shape:",some_tensor.shape)
print("Device:",some_tensor.device)

Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


## **`Manipulating Tensors`**
[Tutorial - 26](https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32656966#content)

***`Tensor Operation:`***



---


1.   Addition
2.   Multiplication (Element Wise)
3.   Division
4.   Matrix Multiplication





In [ ]:
new_tensor = torch.tensor([1, 2, 3])
new_tensor + 10

tensor([11, 12, 13])

In [ ]:
new_tensor - 10

tensor([-9, -8, -7])

In [ ]:
new_tensor * 100

tensor([100, 200, 300])

In [ ]:
new_tensor / 1

tensor([1., 2., 3.])

In [ ]:
new_tensor % 1

tensor([0, 0, 0])

In [ ]:
new_tensor // 1

tensor([1, 2, 3])

In [ ]:
new_tensor2 = torch.tensor([4, 5 ,6])

In [ ]:
torch.matmul(new_tensor,new_tensor2)

tensor(32)

There are mainly two ways to perform multiplication in neural network and deep learning:


1.   Elementwise Multiplication
2.   Matrix Multiplication



In [ ]:
new_tensor3 = torch.tensor([[1,2,3],
                            [4,5,6]])
new_tensor3

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
new_tensor4 = torch.tensor([[7,8],
                            [9,10],
                            [11,12]])
new_tensor4

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
torch.matmul(new_tensor3,new_tensor4)

tensor([[ 58,  64],
        [139, 154]])

There are mainly two rules which should be rememberd:
1. The **inner dimension** must match:

  `(3,2) @ (3,2)` Wont work

  `(2,3) @ (3,2)` will work

  `(3,2) @ (2,3)`
 will work

2. The resulting matrix has a shape of **outer dimension**.

  `(2,3) @ (3,2) -> (2,2)`

  `(3,2) @ (2,3) -> (3,3)`

Tensor Shape errors - [Tutorial - 29](https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32656976#content)

In [ ]:
Tensor_A = torch.tensor([[1,2,3],
                         [4,5,6]])
Tensor_A

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
Tensor_B = torch.tensor([[7,8,9],
                         [10,11,12]])
Tensor_B

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.matmul(Tensor_A,Tensor_B)

tensor([[ 50,  68],
        [122, 167]])

In [ ]:
Tensor_A.shape

torch.Size([2, 3])

In [ ]:
Tensor_B.shape

torch.Size([2, 3])

`Tensor_A and Tensor_B shapes cannot be multiplied` - To hand this kind of error, we can use **Transpose method**, which can be use with **T**.

In [ ]:
Tensor_B = Tensor_B.T #Transpose method

In [ ]:
Tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
torch.matmul(Tensor_A,Tensor_B)

tensor([[ 50,  68],
        [122, 167]])

Finding the ***Min,Mean,Max,Sum*** (Tensor aggregation)

---




In [ ]:
import torch

In [ ]:
random_tensor = torch.arange(0,100,10)

In [ ]:
random_tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(random_tensor)
random_tensor.min()

tensor(0)

In [ ]:
random_tensor.min()

tensor(0)

In [ ]:
torch.mean(random_tensor.type(torch.float32))

tensor(45.)

In [ ]:
torch.max(random_tensor)

tensor(90)

In [ ]:
torch.sum(random_tensor)

tensor(450)

Finding the **postional min and max**

---




In [ ]:
random_tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.argmin(random_tensor)

tensor(0)

In [ ]:
torch.argmax(random_tensor)

tensor(9)

[Tutorial - 32](https://https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32656982#content)

Reshaping, Stacking, squeezing and unsqueezing tensors

```Reshaping :- Reshapes the input tensor to a defined shape```

```View :- Returns the value of input tensor of certain shape but keep the same memory as the original tensor```

```stacking :- Combine multiple tensors on top of each other (vstack) or side by side```


```squeez :- Removes all 1 dimension from the tensor ```

```Unsqueez :- Add 1 dimension to a target tensor```

```permute :- Return a view of input with dimension permuted in certain way```


In [ ]:
x = torch.arange(1.,10.)

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
#Reshape
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the View
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#When we will change z, it will also change x, because both shares the same memory as the original input.
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Squeeze method, removes all single dimension

x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.squeeze() , x_reshaped.squeeze().shape


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_unsqueezed = x_reshaped.unsqueeze(dim=0)
x_unsqueezed

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])



---



---



Tutorial : - 34

[Selecting Data from the Tensors (indexing)](https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32668426#content)

**Indexing in Pytorch is same as indexing in numpy**

In [3]:
tensor_a = torch.arange(1,10).reshape(1,3,3)
tensor_a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [4]:
#Lets index on the tensor
tensor_a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
tensor_a[0][0]

tensor([1, 2, 3])

In [7]:
tensor_a[0][0][0]

tensor(1)

In [13]:
tensor_a[0][1]

tensor([4, 5, 6])

In [14]:
tensor_a[0][1]

tensor([4, 5, 6])

In [16]:
#You can also use ":"  to select all target dimension

In [22]:
tensor_a[:, 0]

tensor([[1, 2, 3]])

In [43]:
tensor_a[:, 1:2, 1:2]

tensor([[[5]]])



---



---



Pytorch Tensors and NumPy

 [Tutorial - 35](https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32668444#conten
 )

In [45]:
import numpy as np

In [46]:
array = np.arange(1.0,8.0)

In [48]:
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note ⚓ : When you convert array from numpy to pytorch tensors, the type of pytorch tensors will be the same as numpy array. So you have to change after converting from the array to the tensors.

In [49]:
new_numpy = tensor_a.numpy()

In [50]:
new_numpy

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

*Reproducbility (Trying To take random out of random)*

In short How neural network learns?

 `Starts with random numbers -> tensor Operations -> Update random numbers to try and make them better representation of data -> again -> again`

 To reduce randomness in neural nertwork or PyTorch, we can use concept  ***random seed***

In [58]:
RANDOM_SEED = 100
torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3,4)

random_tensor_a,random_tensor_b


(tensor([[0.1117, 0.8158, 0.2626, 0.4839],
         [0.6765, 0.7539, 0.2627, 0.0428],
         [0.2080, 0.1180, 0.1217, 0.7356]]),
 tensor([[0.1117, 0.8158, 0.2626, 0.4839],
         [0.6765, 0.7539, 0.2627, 0.0428],
         [0.2080, 0.1180, 0.1217, 0.7356]]))

In [59]:
random_tensor_a == random_tensor_b

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [2]:
!nvidia-smi

Tue Mar 19 07:45:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--